server:
  port: 9001
spring:
  liquibase:
    change-log: classpath:db/changelog/master.xml
    enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class: org.postgresql.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    org:
      springframework:
        security : DEBUG

updatestatus:
  schedulting:
    enabled: true


security:
  jwt:
    secret-key: verysecretkeyfghjkqwertyui
